" variables
let g:neosolarized_contrast = "normal"
let g:neosolarized_visibility = "normal"
let g:neosolarized_vertSplitBgTrans = 1
let g:neosolarized_bold = 1
let g:neosolarized_underline = 1
let g:neosolarized_italic = 0
let g:neosolarized_termBoldAsBright = 1

" settings
set number
set mouse=a
set termguicolors
set background=dark

"  autocmd
autocmd InsertLeave,TextChanged * update

" mappings
nnoremap <silent><Space>q <cmd>quit<CR>
nnoremap <silent><Space>e <cmd>Explore<CR>

colorscheme NeoSolarized
