format="$username$directory$all"
right_format = "$time"

[username]
format = "[ $user]($style) in "
style_user = "bold #f7768e"
style_root = "bold #f7768e"
show_always = true

[directory]
format = "[$path]($style) "
style = "bold #7dcfff"

[time]
disabled = false
format = "[ $time]($style) "
use_12hr = true
style = "bold #bb9af7"
